# Generated by Django 2.1.5 on 2019-01-27 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20190126_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contactno',
            field=models.IntegerField(max_length=10),
        ),
    ]
