# Generated by Django 2.1.5 on 2019-02-01 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20190127_0350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='email',
            new_name='father_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='lname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='pwd',
            new_name='mother_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='sfname',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='rno',
            new_name='roll_no',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='smname',
            new_name='student_email',
        ),
    ]
