# Generated by Django 2.1.5 on 2019-02-01 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20190201_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(auto_created=True, max_length=20, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=20)),
                ('dept_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.CharField(auto_created=True, max_length=20, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=20)),
                ('dept_HOD', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.CharField(auto_created=True, max_length=20, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=100)),
                ('course_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='user_login',
            fields=[
                ('user_email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='contactno',
            field=models.CharField(max_length=10),
        ),
        migrations.AddField(
            model_name='user_login',
            name='roll_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Student'),
        ),
    ]
