# Generated by Django 2.1.5 on 2019-02-01 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20190201_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_login',
            name='roll_no',
        ),
    ]
